[hotkeys]

[general]
# Optional: Returns cursor to original spot after you click/exit
restore_cursor_position = true 

[hints]
enabled = true
# These are the keys you type to select a label
hint_characters = "asdfghjkl" 

[scroll]
# Standard Vim-like scroll speeds
scroll_step = 50


include_menubar_hints = true # top menubar
additional_menubar_hints_targets = [
    "com.apple.TextInputMenuAgent",
    "com.apple.controlcenter",
    "com.apple.systemuiserver",
    "com.y3owk1n.neru",
]
include_dock_hints = false # dock plus mission control
include_nc_hints = true # notification center
include_stage_manager_hints = false # stage manager
include_pip_hints = false # native picture-in-picture controls
include_screen_capture_hints = false # screen capture controls
detect_mission_control = true
