#!/usr/bin/env python3
"""Generate the Hammerflow [a] app-launcher menu from FlashSpace profiles.

FlashSpace's profiles.json is the single source of truth for which apps live in
which workspace. This script mirrors that structure into home.toml as a leader-key
menu:  f18 a <workspace-letter> <app-key>  ->  launch/focus that app.

Apps are launched by bundle identifier (hs.application.launchOrFocusByBundleID),
which is robust against app-name vs bundle-name mismatches (e.g. "Code" vs
"Visual Studio Code").

Usage:
    python3 scripts/gen_flashspace_apps.py [--profile NAME]

Re-run whenever you add/remove apps in FlashSpace.
"""

import argparse
import json
import re
import sys
from pathlib import Path

PROFILES = Path.home() / ".config" / "flashspace" / "profiles.json"
HOME_TOML = Path(__file__).resolve().parent.parent / "hammerspoon" / ".hammerspoon" / "home.toml"

BEGIN = "# >>> flashspace-apps (generated by scripts/gen_flashspace_apps.py) >>>"
END = "# <<< flashspace-apps end <<<"

# Optional nice mnemonics: app name -> preferred key (falls back to auto if taken).
PREFERRED = {
    "Code": "v",            # VS Code
    "Microsoft Edge": "e",
    "Google Chrome": "c",
    "OBS Studio": "o",
    "Windows App": "w",
}

# Friendlier labels shown in the popup (app name -> label).
LABELS = {
    "Code": "VS Code",
}


def workspace_key(name: str) -> str | None:
    """'Source (S)' -> 's'. Returns None if no single-letter tag is present."""
    m = re.search(r"\(([A-Za-z])\)\s*$", name)
    return m.group(1).lower() if m else None


def assign_key(name: str, taken: set[str]) -> str:
    """Pick a stable, free single-char key for an app within its workspace."""
    if name in PREFERRED and PREFERRED[name] not in taken:
        k = PREFERRED[name]
        taken.add(k)
        return k
    for ch in re.sub(r"[^a-z0-9]", "", name.lower()):
        if ch not in taken:
            taken.add(ch)
            return ch
    for ch in "abcdefghijklmnopqrstuvwxyz0123456789":
        if ch not in taken:
            taken.add(ch)
            return ch
    raise RuntimeError(f"no free key for {name!r} (>36 apps in one workspace?)")


def toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate(profile_name: str | None) -> str:
    data = json.loads(PROFILES.read_text())
    profiles = data["profiles"]
    profile = next((p for p in profiles if p.get("name") == profile_name), None) if profile_name else profiles[0]
    if profile is None:
        sys.exit(f"profile {profile_name!r} not found; have: {[p.get('name') for p in profiles]}")

    out = [BEGIN, "[a]", 'label = "[apps]"', ""]
    for ws in profile.get("workspaces", []):
        wkey = workspace_key(ws.get("name", ""))
        apps = ws.get("apps", [])
        if not wkey or not apps:
            continue
        out.append(f"[a.{wkey}]")
        out.append(f"label = {toml_str('[' + ws['name'] + ']')}")
        taken: set[str] = set()
        for app in apps:
            name = app.get("name")
            bundle = app.get("bundleIdentifier")
            if not name or not bundle:
                continue
            key = assign_key(name, taken)
            action = f"hs:hs.application.launchOrFocusByBundleID('{bundle}')"
            label = LABELS.get(name, name)
            out.append(f"{key} = [{toml_str(action)}, {toml_str(label)}]")
        out.append("")
    out.append(END)
    return "\n".join(out).rstrip() + "\n"


def splice(toml_text: str, block: str) -> str:
    if BEGIN in toml_text and END in toml_text:
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
        return pattern.sub(block.rstrip(), toml_text)
    sep = "" if toml_text.endswith("\n\n") else ("\n" if toml_text.endswith("\n") else "\n\n")
    return toml_text + sep + "\n" + block


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", help="FlashSpace profile name (default: first)")
    ap.add_argument("--print", action="store_true", help="print block, don't write")
    args = ap.parse_args()

    block = generate(args.profile)
    if args.print:
        print(block, end="")
        return
    HOME_TOML.write_text(splice(HOME_TOML.read_text(), block))
    print(f"updated {HOME_TOML}")


if __name__ == "__main__":
    main()
